export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_GET_USER_PERMISSIONS = "AUTH_GET_USER_PERMISSIONS";

export const GET_WORK_ORDERS = "GET_WORK_ORDERS";
export const UPDATE_WORK_ORDER_STATUS = "UPDATE_WORK_ORDER_STATUS";
export const GET_CURRENT_WORK_ORDER = "GET_CURRENT_WORK_ORDER";
